import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useFieldArray, Controller } from "react-hook-form";
import TextInput from "../../../components/Form/Input/TextInput";
export default function StrengthFields({ control, }) {
    const { fields, append, remove } = useFieldArray({
        control,
        name: "details.sets",
    });
    return (_jsxs(_Fragment, { children: [_jsx("p", { className: "w-full text-xs font-semibold text-green-700 uppercase tracking-widest", children: "Sets" }), fields.map((field, index) => (_jsxs("div", { className: "w-full bg-gray-800/50 border border-gray-700 rounded-lg p-3 flex flex-col gap-3", children: [_jsxs("div", { className: "flex gap-3", children: [_jsx(Controller, { name: `details.sets.${index}.reps`, control: control, render: ({ field }) => (_jsxs("div", { className: "flex-1 flex flex-col gap-1", children: [_jsx("label", { htmlFor: `reps-${index}`, className: "text-sm text-gray-400", children: "Repeticiones" }), _jsx(TextInput, { id: `reps-${index}`, type: "number", value: field.value ?? "", onChange: (v) => field.onChange(v === "" ? undefined : Number(v)), placeholder: "Ej: 12" })] })) }), _jsx(Controller, { name: `details.sets.${index}.weightKg`, control: control, render: ({ field }) => (_jsxs("div", { className: "flex-1 flex flex-col gap-1", children: [_jsx("label", { htmlFor: `weight-${index}`, className: "text-sm text-gray-400", children: "Peso (kg)" }), _jsx(TextInput, { id: `weight-${index}`, type: "number", value: field.value ?? "", onChange: (v) => field.onChange(v === "" ? undefined : Number(v)), placeholder: "Ej: 60" })] })) })] }), _jsx("button", { type: "button", onClick: () => remove(index), className: "text-red-400 text-xs self-end hover:text-red-300 transition cursor-pointer", children: "Eliminar set" })] }, field.id))), _jsx("button", { type: "button", onClick: () => append({ reps: 0, weightKg: 0 }), className: "w-full border border-green-700 text-emerald-600 rounded-lg py-2 text-sm hover:bg-green-900/30 transition cursor-pointer", children: "+ Agregar set" })] }));
}
